apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: metacoding
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_DATABASE: metadb
  MYSQL_USER: metacoding #root 계정으로는 접속 불가
  MYSQL_PASSWORD: metacoding1234
