apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: metacoding
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://db-service:3306/metadb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_DATA_REDIS_HOST: redis-service
  SPRING_DATA_REDIS_PORT: "6379"

