services:
  app1:
    image: app1
    ports:
      - 8000:80
    build:
      context: ./app1
      dockerfile: Dockerfile
  app2:
    image: app2
    ports:
      - 9000:80
    build:
      context: ./app2
      dockerfile: Dockerfile
  lb:
    image: lb
    ports:
      - 80:80
    build:
      context: ./lb
      dockerfile: Dockerfile
